source "https://rubygems.org"

ruby "1.9.3"
gem "rails", "3.2.13"

gem "active_model_serializers", "~> 0.8.0"
gem "puma"

group :development do
  gem "debugger"
  gem "foreman"
  gem "quiet_assets"
  gem "sqlite3"
end